name: k3s-nix-build-on-demand-docker-v2
on:
  workflow_dispatch:
    inputs:
      nodeName:
        type: choice
        required: true
        description: Choose which node to build
        options:
          - master
          - kube-node-1
          - kube-node-2
          - kube-node-3

jobs:
  build-node-image:
    name: Build node image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Check nix.conf
        run: cat /etc/nix/nix.conf
      - name: Register binfmt
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Test binfmt availability
        run: |
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
      - name: Build SD Image
        run: |
          docker build --build-arg NODE_NAME=${{ github.event.inputs.nodeName }} -t my-nixos-sd-image .
      - name: Extract image
        run: |
          container_id=$(docker create my-nixos-sd-image)
          docker cp $container_id:$(find /sd-image/result -type f -name 'nixos-sd-image*') .
          docker rm $container_id
      - uses: actions/upload-artifact@v4
        with:
          name: sd-image.img
          path: ./nixos-sd-image*
